### ISSUE TITLE
Pages not loading

### ISSUE THREAD

**Issue by kosvrouvas** [carrieforde/Aurora-Theme#1]
Hello, I'm experimenting with WordPress React themes and you've done a great work!

One problem I have, is that pages do not load in aurora theme. I noticed this is happening on your demo too..

**Comment by carrieforde** [comment]
Hi @kosvrouvas, you are completely correct. I've been away from this project for a bit, but it looks like I've only set up Redux to pull posts, and not other post types (including pages). If I recall correctly, it's a bit tricky to route to pages because they have a different base endpoint than posts.

I'll have a look into this and see what I can do!
